spring:
  application:
    name: ai-news-intel
  profiles:
    active: local

server:
  port: ${PORT:8080}

app:
  cors:
    allowed-origin: ${ALLOWED_ORIGIN:http://localhost:5173}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000 # 24 hours

news:
  feeds:
    - name: BBC News
      url: http://feeds.bbci.co.uk/news/rss.xml
    - name: TechCrunch
      url: https://techcrunch.com/feed/
    - name: The Hindua
      url: https://www.thehindu.com/news/national/feeder/default.rss

gemini:
  api-key: ${GEMINI_API_KEY}
